#!/usr/bin/env python3
"""Validate a commit message against Conventional Commits v1.0.0.

Invoked by the lefthook `commit-msg` hook with the path to the file holding
the proposed commit message (git's `$1` / `COMMIT_EDITMSG`):

  scripts/check-commit-msg.py <path-to-commit-msg-file>

Exit 0 if the message conforms, 1 otherwise. On failure a short, actionable
explanation is printed to stderr. stdout is left empty.

Spec: https://www.conventionalcommits.org/en/v1.0.0/

Summary of what is enforced on the **header** (first line):

  <type>[optional scope][optional !]: <description>

- `type` is a non-empty lowercase-ish term (letters only here, e.g. feat, fix).
- optional `(scope)` — any non-empty text without a newline or `)`.
- optional `!` before the colon to flag a breaking change.
- a literal `: ` (colon + single space) terminator.
- a non-empty `description`.

Merge/revert/fixup/squash autogenerated commits are skipped (git owns those).
"""

import re
import sys

# Conventional Commit types from the spec + the Angular convention it cites.
# `feat` and `fix` are the only spec-mandated ones; the rest are the widely
# used set. Keep lowercase.
ALLOWED_TYPES = (
    "feat",
    "fix",
    "build",
    "chore",
    "ci",
    "docs",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
)

# <type>(<scope>)?!?: <description>
HEADER_RE = re.compile(
    r"^(?P<type>[a-z]+)"
    r"(?:\((?P<scope>[^()\r\n]+)\))?"
    r"(?P<breaking>!)?"
    r": "
    r"(?P<description>.+)$"
)

# Commit message prefixes git generates itself — never our place to reject.
SKIP_PREFIXES = (
    "Merge ",
    "Revert ",
    "fixup! ",
    "squash! ",
    "amend! ",
)


def first_meaningful_line(text: str) -> str:
    """Return the first non-blank, non-comment line (the header)."""
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        if line.strip() == "":
            continue
        return line
    return ""


def fail(header: str, reason: str) -> int:
    print("commit-msg: not a valid Conventional Commit.", file=sys.stderr)
    print(f"  reason: {reason}", file=sys.stderr)
    if header:
        print(f"  header: {header!r}", file=sys.stderr)
    print("", file=sys.stderr)
    print("  expected: <type>[(scope)][!]: <description>", file=sys.stderr)
    print(f"  types:    {', '.join(ALLOWED_TYPES)}", file=sys.stderr)
    print("  examples: feat(parser): add array support", file=sys.stderr)
    print("            fix: handle empty input", file=sys.stderr)
    print("            feat!: drop Node 18 support", file=sys.stderr)
    print("  spec:     https://www.conventionalcommits.org/en/v1.0.0/", file=sys.stderr)
    return 1


def validate(text: str) -> int:
    header = first_meaningful_line(text)

    if header == "":
        return fail(header, "commit message is empty")

    if header.startswith(SKIP_PREFIXES):
        return 0

    match = HEADER_RE.match(header)
    if not match:
        return fail(header, "header does not match '<type>[(scope)][!]: <description>'")

    commit_type = match.group("type")
    if commit_type not in ALLOWED_TYPES:
        return fail(header, f"unknown type {commit_type!r}")

    if match.group("scope") is not None and match.group("scope").strip() == "":
        return fail(header, "scope parentheses are present but empty")

    if match.group("description").strip() == "":
        return fail(header, "description is empty")

    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: check-commit-msg.py <path-to-commit-msg-file>", file=sys.stderr)
        return 2

    path = argv[1]
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError as err:
        print(f"commit-msg: cannot read {path!r}: {err}", file=sys.stderr)
        return 2

    return validate(text)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
